version: '3.11.1'

services:
  web:
    build: .
    command: python /drfecom/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-55etnoy(2ag-+#%=63wn^)h673b$jp^!*a66o7%%+pr@viwjp#
      - DEBUG=1
    volumes:
     - .:/drfecom
    ports:
     - 8000:8000
    depends_on:
     - db
  db:
    image: postgres:11
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  postgres_data:
